name: 'Setup Symfony Demo Application'
description: 'Install and cache PHP dependencies'
inputs:
  tools:
    description: 'CSV list of tools to install'
    required: false
    default: 'composer'
runs:
  using: 'composite'
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        extensions: 'intl, mbstring, pdo_sqlite'
        php-version: '8.1'
        tools: 'symfony, ${{ inputs.tools }}'
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
    - name: Install dependencies
      run: composer install --no-interaction --no-progress
      shell: bash
    - name: Check requirements
      run: symfony check:requirements
      shell: bash
